language: go

go:
  - 1.11.x
  - 1.12.x
  - master

os:
  - linux

addons:
  apt:
    packages:
      - portaudio19-dev
      - libwebkit2gtk-4.0-dev
      - swig

before_script:
  - make deps

script:
  - make fmt-check
  - make gen
  - make webview
