language: go

go:
  - 1.11.x
  - 1.12.x
  - master

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install portaudio19-dev

before_script:
  - echo "Installing sphinxbase..."
  - git clone https://github.com/cmusphinx/sphinxbase.git
  - cd sphinxbase && ./autogen.sh && ./configure && make -j 4 && sudo make install
  - echo "Installing PocketSphinx..."
  - git clone https://github.com/cmusphinx/pocketsphinx.git
  - cd pocketsphinx && ./autogen.sh && ./configure && sudo make install

script:
  - make fmt-check
  - make webview
