%YAML 1.1
---
# 实体
entities:
# 病的名字
- disease
# 食物名
- food
# 模式
- mode
# 具体的时间
- time
# 电话号码
- phone_number
# 价格
- price
intents:
# 确认
- affirm
# 询问名字
- ask_name
# 拒绝
- deny
# 再见
- goodbye
# 问候
- greet
# 询问时间
- inform_time
# 咨询生病问题
- medical
# 请求搜索
- request_search
# 搜索饭店
- restaurant_search
# 切换模式
- switch_mode
# 感谢
- thanks
