version: v1
services:
  - name: localhub
    image: aiicy-hub
    replica: 1
    mounts:
      - name: localhub-conf
        path: etc/aiicy
        readonly: true
      - name: localhub-cert
        path: var/db/aiicy/cert
        readonly: true
      - name: localhub-data
        path: var/db/aiicy/data
      - name: localhub-log
        path: var/log/aiicy
      # native process mode only
      - name: aiicy-hub-bin
        path: lib/aiicy/aiicy-hub
        readonly: true
  - name: function
    image: aiicy-function
    replica: 1
    mounts:
      - name: function-conf
        path: etc/aiicy
        readonly: true
      - name: function-log
        path: var/log/aiicy
      # native process mode only
      - name: aiicy-function-bin
        path: lib/aiicy/aiicy-function
        readonly: true
  - name: application-nlu
    image: aiicy-function-python3
    replica: 0
    mounts:
      # application-nlu
      - name: application-nlu-conf
        path: etc/aiicy
        readonly: true
      - name: application-nlu-code
        path: var/db/aiicy/application-nlu
        readonly: true
      # native process mode only
      - name: aiicy-function-python3-bin
        path: lib/aiicy/aiicy-function-python3
        readonly: true
volumes:
  # hub
  - name: localhub-conf
    path: var/db/aiicy/localhub-conf
  - name: localhub-data
    path: var/db/aiicy/localhub-data
  - name: localhub-cert
    path: var/db/aiicy/localhub-cert-only-for-test
  - name: localhub-log
    path: var/db/aiicy/localhub-log
  # function
  - name: function-conf
    path: var/db/aiicy/function-conf
  - name: function-log
    path: var/db/aiicy/function-log
  # application-nlu
  - name: application-nlu-conf
    path: var/db/aiicy/application-nlu-conf
  - name: application-nlu-code
    path: var/db/aiicy/application-nlu-code
  # bin, native process mode only
  - name: aiicy-hub-bin
    path: var/db/aiicy/aiicy-hub
  - name: aiicy-function-bin
    path: var/db/aiicy/aiicy-function
  - name: aiicy-function-python3-bin
    path: var/db/aiicy/aiicy-function-python3
