hub:
  address: tcp://0.0.0.0:1883
  username: test
  password: hahaha
  keepalive: -1 # no ping/pong
logger:
  path: var/log/homo/hub.log
  level: 'debug'
  mode: 'console'
  format: 'text'
  age:
    max: 15
  size:
    max: 50
  backup:
    max: 15
rules:
  - clientid: func-python3-sayhi-1
    subscribe:
      topic: t
    function:
      name: python3-sayhi
    publish:
      topic: t/py3hi
  - clientid: application-nlu-1
    subscribe:
      topic: t
    function:
      name: application-nlu
    publish:
      topic: t/nlu
functions:
  - name: python3-sayhi
    service: function-python3-sayhi
  - name: application-nlu
    service: application-nlu