language: "zh"
project: "rasa"
fixed_model_name: "ini"
path: "models"

pipeline:
- name: "nlp_mitie"
  model: "data/rasa/total_word_feature_extractor_zh.dat"
- name: "tokenizer_jieba"
  dictionary_path: "jieba_userdict"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn"
