hub:
  address: tcp://0.0.0.0:1883
  username: test
  password: hahaha
  keepalive: -1 # no ping/pong
logger:
  path: var/log/aiicy/function.log
  level: 'debug'
  mode: 'console'
  format: 'text'
  age:
    max: 15
  size:
    max: 50
  backup:
    max: 15
rules:
  - clientid: application-nlu-1
    subscribe:
      topic: t
    function:
      name: application-nlu
    publish:
      topic: t/nlu
functions:
  - name: application-nlu
    service: application-nlu
