version: "3"
app_version: v2
services:
  aiicy-function:
    image: aiicy-function
    replica: 1
    volumes:
    - var/db/aiicy/aiicy-function-conf:etc/aiicy:ro
    - var/db/aiicy/aiicy-function:lib/aiicy/aiicy-function:ro
  aiicy-hub:
    image: aiicy-hub
    replica: 1
    volumes:
    - var/db/aiicy/aiicy-hub-conf:etc/aiicy:ro
    - var/db/aiicy/aiicy-hub:lib/aiicy/aiicy-hub:ro
    - var/db/aiicy/hub-cert-only-for-test:var/db/aiicy/cert:ro
