functions:
  - name: 'python3-sayhi'
    handler: 'hi.handler'
    codedir: 'var/db/aiicy/function-sayhi'
  - name: 'application-nlu'
    handler: 'nlu.handler'
    codedir: 'var/db/aiicy/application-nlu'
logger:
  path: var/log/aiicy/function.log
  level: 'debug'
